name: general-dl
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools>=68,<70
  - numpy
  - ruff
  - pytest
  - pytest-mock
  - tensorflow
  - keras
  - matplotlib
  - pip:
      - keras-hub==0.19.0
      - gradio
variables:
  ENV: test
